project:
  uuid: cecaf59b-fbbb-4aed-9632-b89bfcd47be0
  slug: openshot-qt
  node_id: 752e6076aa27
  build_id: 5eec70ad-2651-4847-aecf-496eb7530db4
vcs:
  type: git
agents:
  available:
  - codex
  auto_commit: true
  lint_on_edit: false
